const alumni = [
  {
    name: 'Deepinder Goyal',
    from: 'IIT Delhi',
    now: 'Founder, Eternal (Zomato)',
    tag: 'Founder',
    photo: 'DeepinderGoyal',
    blurb: 'Built Zomato and Blinkit into Eternal, a listed consumer internet group. IIT Delhi Mathematics and Computing, 2005.',
    href: 'https://www.zomato.com',
  },
  {
    name: 'Vidit Aatrey',
    from: 'IIT Delhi',
    now: 'Co-founder, Meesho',
    tag: 'Founder',
    photo: '',
    blurb: 'Co-founded Meesho with batchmate Sanjeev Barnwal. The social commerce company listed in 2025.',
    href: 'https://www.meesho.com',
  },
  {
    name: 'Sachin Bansal',
    from: 'IIT Delhi',
    now: 'Founder, Navi',
    tag: 'Founder',
    photo: 'SachinBansal',
    blurb: 'Co-founded Flipkart, then built Navi. In August 2026 Navi raised $100 million from Prosus at about $1.3 billion, ahead of a planned IPO.',
    href: 'https://www.navi.com',
  },
  {
    name: 'Harsh Jain',
    from: 'IIT Delhi',
    now: 'Co-founder, Groww',
    tag: 'Founder',
    photo: '',
    blurb: 'Co-founder and COO of Groww. Electrical Engineering and M.Tech from IIT Delhi. Groww raised $200 million in 2025 at a $7 billion valuation and listed thereafter.',
    href: 'https://groww.in',
  },
  {
    name: 'Yashish Dahiya',
    from: 'IIT Delhi',
    now: 'Co-founder, Policybazaar',
    tag: 'Founder',
    photo: '',
    blurb: 'B.Tech Textile Technology, 1994. Co-founded PB Fintech (Policybazaar), now a listed insurance marketplace.',
    href: 'https://www.policybazaar.com',
  },
  {
    name: 'Sanjeev Barnwal',
    from: 'IIT Delhi',
    now: 'Co-founder & CTO, Meesho',
    tag: 'Founder',
    photo: '',
    blurb: 'Electrical Engineering, 2012. Co-founded Meesho and remains CTO of the listed social commerce company.',
    href: 'https://www.meesho.com',
  },
  {
    name: 'Binny Bansal',
    from: 'IIT Delhi',
    now: 'Co-founder, Flipkart',
    tag: 'Founder',
    photo: '',
    blurb: 'Co-founded Flipkart with Sachin Bansal. Named in IIT Delhi’s 2026 Alumni Impact Report among the institute’s defining ecommerce founders.',
    href: 'https://www.flipkart.com',
  },
  {
    name: 'Vivek Raghavan',
    from: 'IIT Delhi',
    now: 'Co-founder, Sarvam AI',
    tag: 'Founder',
    photo: '',
    blurb: 'Co-founded Sarvam AI. The company reached unicorn status in 2026 and has been in talks to raise a large round at about $1.5 billion.',
    href: 'https://www.sarvam.ai',
  },
  {
    name: 'Ashneer Grover',
    from: 'IIT Delhi',
    now: 'Co-founder, BharatPe',
    tag: 'Founder',
    photo: 'AshneerGrover',
    blurb: 'B.Tech Civil Engineering, IIT Delhi. Co-founded BharatPe, a merchant payments unicorn, and spoke at BECon 2026.',
    href: 'https://bharatpe.com',
  },
  {
    name: 'Rohit Bansal',
    from: 'IIT Delhi',
    now: 'Co-founder, Snapdeal & Titan Capital',
    tag: 'Founder',
    photo: 'RohitBansal',
    blurb: 'IIT Delhi, 2006. Co-founded Snapdeal (AceVector) and Titan Capital. Unicommerce, which he helped operate, listed in 2024.',
    href: 'https://www.titancapital.vc',
  },
  {
    name: 'Jyoti Bansal',
    from: 'IIT Delhi',
    now: 'Founder, Harness',
    tag: 'Founder',
    photo: '',
    blurb: 'Computer Science, 1995 to 1999. Founded AppDynamics, sold to Cisco for $3.7 billion, then built Harness, a software-delivery platform.',
    href: 'https://www.harness.io',
  },
  {
    name: 'Ashutosh Garg',
    from: 'IIT Delhi',
    now: 'Co-founder, Eightfold AI',
    tag: 'Founder',
    photo: '',
    blurb: 'IIT Delhi B.Tech, then a PhD at Illinois. Co-founded Bloomreach and Eightfold AI, a talent platform valued above $2 billion.',
    href: 'https://eightfold.ai',
  },
  {
    name: 'Rishabh Goel',
    from: 'IIT Delhi',
    now: 'Co-founder, Credgenics',
    tag: 'Founder',
    photo: '',
    blurb: 'Engineering Physics, 2016. Credgenics has raised about $79 million, including a $50 million Series B, and acquired Arrise in 2025.',
    href: 'https://credgenics.com',
  },
  {
    name: 'Arpit Dhupar',
    from: 'IIT Delhi',
    now: 'Co-founder, Chakr Innovation',
    tag: 'Founder',
    photo: '',
    blurb: 'Started Chakr at IIT Delhi in 2016. The cleantech company raised $23 million in 2025, led by Iron Pillar.',
    href: 'https://www.chakr.in',
  },
  {
    name: 'Neetu Yadav',
    from: 'IIT Delhi',
    now: 'Co-founder, Animall',
    tag: 'Founder',
    photo: '',
    blurb: 'Civil Engineering, 2016. Co-founded Animall with Kirti Jangra. The dairy marketplace is valued around ₹565 crore, backed by Sequoia and Nexus.',
    href: 'https://www.animall.in',
  },
  {
    name: 'Ankit Pruthi',
    from: 'IIT Delhi',
    now: 'Co-founder, Unicommerce',
    tag: 'Founder',
    photo: '',
    blurb: 'Co-founded Unicommerce at IIT Delhi with classmates. The ecommerce SaaS company listed in August 2024.',
    href: 'https://unicommerce.com',
  },
  {
    name: 'Alok Mittal',
    from: 'IIT Delhi',
    now: 'Co-founder, Indifi',
    tag: 'Mentor',
    photo: 'AlokMittal',
    blurb: 'Computer Science, 1994. Builds SME lending at Indifi, which raised a further round in 2026. Mentors founders in eDC Venture Studio.',
    href: 'https://www.indifi.com',
  },
  {
    name: 'Bharti Singhla',
    from: 'IIT Delhi',
    now: 'Co-founder, Chakr Innovation',
    tag: 'Mentor',
    photo: '',
    blurb: 'Chemical Engineering, 2015. Co-founded Chakr Innovation. Mentors eDC Venture Studio founders while the company scales after its 2025 round.',
    href: 'https://www.chakr.in',
  },
]

export default alumni
