const alumni = [
  {
    name: 'Deepinder Goyal',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Zomato',
    tag: 'Founder',
    photo: 'DeepinderGoyal',
    blurb: 'Building restaurant discovery and food delivery after his time in the IIT Delhi entrepreneurship community.',
    href: 'https://www.zomato.com',
  },
  {
    name: 'Sachin Bansal',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Flipkart',
    tag: 'Founder',
    photo: 'SachinBansal',
    blurb: 'Went on to co-found Flipkart, one of India’s defining internet companies.',
    href: 'https://www.flipkart.com',
  },
  {
    name: 'Kunal Bahl',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Snapdeal',
    tag: 'Founder',
    photo: 'KunalBahl',
    blurb: 'Co-founded Snapdeal and remains closely involved with eDC programmes as a speaker and investor.',
    href: 'https://www.snapdeal.com',
  },
  {
    name: 'Sanjeev Bikhchandani',
    from: 'eDC IIT Delhi',
    now: 'Founder, Info Edge',
    tag: 'Founder',
    photo: 'SanjeevBikhchandani',
    blurb: 'Founded Info Edge (Naukri) and has backed a generation of Indian consumer internet companies.',
    href: 'https://www.infoedge.in',
  },
  {
    name: 'Alok Mittal',
    from: 'eDC IIT Delhi',
    now: 'Co-founder & CEO, Indifi',
    tag: 'Mentor',
    photo: 'AlokMittal',
    blurb: 'Builds credit infrastructure for small businesses, and mentors student founders through eDC.',
    href: 'https://www.indifi.com',
  },
  {
    name: 'Peyush Bansal',
    from: 'eDC IIT Delhi',
    now: 'Founder, Lenskart',
    tag: 'Founder',
    blurb: 'Building Lenskart into a leading D2C eyewear brand.',
    href: 'https://www.lenskart.com',
  },
  {
    name: 'Yashish Dahiya',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Policybazaar',
    tag: 'Founder',
    blurb: 'Co-founded Policybazaar, now one of India’s largest insurance marketplaces.',
    href: 'https://www.policybazaar.com',
  },
  {
    name: 'Vidit Aatrey',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Meesho',
    tag: 'Founder',
    blurb: 'Co-founded Meesho, a social commerce platform used by millions of resellers.',
    href: 'https://www.meesho.com',
  },
  {
    name: 'Amod Malviya',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Udaan',
    tag: 'Founder',
    blurb: 'Co-founded Udaan, a B2B trade platform connecting manufacturers, wholesalers, and retailers.',
    href: 'https://www.udaan.com',
  },
  {
    name: 'Arpit Dhupar',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Chakr Innovation',
    tag: 'Founder',
    blurb: 'Building climate-tech to cut diesel emissions, from work that started on the IIT Delhi campus.',
    href: 'https://www.chakr.in',
  },
  {
    name: 'Abhinav Shashank',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, Innovaccer',
    tag: 'Founder',
    blurb: 'Co-founded Innovaccer, a healthcare data platform used by health systems worldwide.',
    href: 'https://www.innovaccer.com',
  },
  {
    name: 'Samay Kohli',
    from: 'eDC IIT Delhi',
    now: 'Co-founder, GreyOrange',
    tag: 'Founder',
    blurb: 'Co-founded GreyOrange, building warehouse robotics used across global supply chains.',
    href: 'https://www.greyorange.com',
  },
]

export default alumni
