import { JPG, PNG } from './images.js'

const avatar = (name) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=302b62&color=ffffff&size=400`

const coreTeam = [
  {
    name: 'Lakshay Goyal',
    position: 'Overall Coordinator',
    image: JPG.Lakshay,
    gmail: '8059800706lakshya@gmail.com',
    linkedin: 'https://www.linkedin.com/in/goellakshay',
  },
  {
    name: 'Dishit Johari',
    position: 'Co-Overall Coordinator',
    image: JPG.Dishit,
    gmail: 'dishitjohari8879@gmail.com',
    linkedin: 'https://www.linkedin.com/in/dishit-johari-001a76237',
  },
  {
    name: 'Aghamarsh Chetluru',
    position: 'Co-Overall Coordinator',
    image: JPG.Aghamarsh,
    gmail: 'aghamarsh.chet@gmail.com',
    linkedin: 'https://www.linkedin.com/in/aghamarsh-chetluru/',
  },
  {
    name: 'Sakshi Sharma',
    position: 'Co-Overall Coordinator',
    image: JPG.Sakshi,
    gmail: 'sakshi20040701@gmail.com',
    linkedin: 'https://www.linkedin.com/in/sakshisharma431',
  },
]

const teamMembers = [
  {
    name: 'Kirti Tekriwal',
    position: 'Events',
    image: avatar('Kirti Tekriwal'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Aditya Singh Thakur',
    position: 'Events',
    image: avatar('Aditya Singh Thakur'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Arnav Singhal',
    position: 'Startup Support',
    image: avatar('Arnav Singhal'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Dhaanya Aditi',
    position: 'Startup Support',
    image: avatar('Dhaanya Aditi'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Madhav Soni',
    position: 'Content & Editorial',
    image: avatar('Madhav Soni'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Tejinder Singh',
    position: 'Content & Editorial',
    image: avatar('Tejinder Singh'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Anant Kumar',
    position: 'Content & Editorial',
    image: avatar('Anant Kumar'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Atharva Deshmukh',
    position: 'Media',
    image: avatar('Atharva Deshmukh'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Shubham Bhardwaj',
    position: 'Media',
    image: avatar('Shubham Bhardwaj'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Adarsh Kumar',
    position: 'Marketing',
    image: avatar('Adarsh Kumar'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Hardik Mahajan',
    position: 'Marketing',
    image: avatar('Hardik Mahajan'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Manan Gupta',
    position: 'Corporate Relations',
    image: avatar('Manan Gupta'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Adarsh Agrawal',
    position: 'Corporate Relations',
    image: avatar('Adarsh Agrawal'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Pratyaksh Khanna',
    position: 'Admin and Finance',
    image: avatar('Pratyaksh Khanna'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Agrima Agarwal',
    position: 'Admin and Finance',
    image: avatar('Agrima Agarwal'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Tanay Singh Lodhi',
    position: 'OC Office',
    image: avatar('Tanay Singh Lodhi'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Swayam Gupta',
    position: 'OC Office',
    image: avatar('Swayam Gupta'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Vaishnavi Saxena',
    position: 'Publicity',
    image: avatar('Vaishnavi Saxena'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Manasvi',
    position: 'Publicity',
    image: avatar('Manasvi'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Prabhav',
    position: 'Technical',
    image: PNG.prabhav,
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Rishabh Sain',
    position: 'Technical',
    image: avatar('Rishabh Sain'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Aarush Bansal',
    position: 'Design',
    image: avatar('Aarush Bansal'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Adithyan S',
    position: 'Design',
    image: avatar('Adithyan S'),
    gmail: '',
    linkedin: '',
  },
  {
    name: 'Rudra Tyagi',
    position: 'Design',
    image: avatar('Rudra Tyagi'),
    gmail: '',
    linkedin: '',
  },
]

export { coreTeam, teamMembers }
